// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2025-2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
//
// @generated by `just gen` from config/connectors.ncl.
// DO NOT EDIT BY HAND — `just gen-check` fails if this file drifts.
//
// The Hexadeca-Connector: a sixteen-protocol unified API over one C-ABI core.
//
// The ORDINAL is the wire contract. A connector tag crosses the FFI boundary
// as a u8, so if Zig, Rust and Idris2 disagree about which number means which
// protocol, every call silently dispatches to the wrong handler — nothing
// crashes, the wrong thing just happens. All three are generated from
// config/connectors.ncl, and tests/hexadeca_wire_order.rs proves they agree.
//
// `implemented` is honest: a connector without a real handler returns
// error.NotImplemented, never a success code. Sixteen stubs that all return 0
// would look like a transport layer and would not be one.

const std = @import("std");

pub const Connector = enum(u8) {
    grpc = 0,
    graphql = 1,
    rest = 2,
    flatbuffers = 3,
    bebop = 4,
    jsonrpc = 5,
    websocket = 6,
    mqtt = 7,
    trpc = 8,
    capnproto = 9,
    soap = 10,
    verisimdb_rest = 11,
    bsp = 12,
    scip = 13,
    ipfs = 14,
    arrow_flight = 15,

    pub fn connectorName(self: Connector) [*:0]const u8 {
        return switch (self) {
            .grpc => "grpc",
            .graphql => "graphql",
            .rest => "rest",
            .flatbuffers => "flatbuffers",
            .bebop => "bebop",
            .jsonrpc => "jsonrpc",
            .websocket => "websocket",
            .mqtt => "mqtt",
            .trpc => "trpc",
            .capnproto => "capnproto",
            .soap => "soap",
            .verisimdb_rest => "verisimdb_rest",
            .bsp => "bsp",
            .scip => "scip",
            .ipfs => "ipfs",
            .arrow_flight => "arrow_flight",
        };
    }

    /// Whether a real handler exists for this protocol.
    pub fn isImplemented(self: Connector) bool {
        return switch (self) {
            .grpc => false,
            .graphql => false,
            .rest => false,
            .flatbuffers => false,
            .bebop => false,
            .jsonrpc => false,
            .websocket => false,
            .mqtt => false,
            .trpc => false,
            .capnproto => false,
            .soap => false,
            .verisimdb_rest => false,
            .bsp => false,
            .scip => false,
            .ipfs => false,
            .arrow_flight => false,
        };
    }

    pub fn describe(self: Connector) [*:0]const u8 {
        return switch (self) {
            .grpc => "gRPC service surface.",
            .graphql => "GraphQL query surface.",
            .rest => "JSON-in/JSON-out over HTTP — the shape idaptik-ffi already speaks, and the intended first transport for the UMS<->game DLC seam.",
            .flatbuffers => "FlatBuffers zero-copy payloads.",
            .bebop => "Bebop binary records.",
            .jsonrpc => "JSON-RPC 2.0 — the intended framing for an editor driving ai-edit `solve` and `check`.",
            .websocket => "Duplex session transport (the game's session relay speaks this).",
            .mqtt => "Pub/sub telemetry.",
            .trpc => "tRPC-style typed procedure calls.",
            .capnproto => "Cap'n Proto RPC.",
            .soap => "SOAP envelopes (legacy interop).",
            .verisimdb_rest => "VerisimDB REST surface.",
            .bsp => "Build Server Protocol.",
            .scip => "Source Code Index Protocol.",
            .ipfs => "Content-addressed DLC distribution.",
            .arrow_flight => "Arrow Flight bulk transfer.",
        };
    }

    /// Decode a wire tag. Returns null for an out-of-range byte rather than
    /// coercing it, so a version mismatch is detected instead of dispatched.
    pub fn fromTag(tag: u8) ?Connector {
        if (tag >= CONNECTOR_COUNT) return null;
        return @enumFromInt(tag);
    }
};

pub const CONNECTOR_COUNT: usize = 16;
pub const IMPLEMENTED_COUNT: usize = 0;

pub const DispatchError = error{
    /// The protocol is declared in the Hexadeca set but has no handler.
    NotImplemented,
    /// The wire tag did not name a connector.
    UnknownConnector,
};

/// Dispatch a request to a connector.
///
/// No connector has a transport handler yet, so this currently returns
/// `NotImplemented` for every tag. That is the honest behaviour: returning a
/// success code from a connector that did nothing is how a stub layer comes
/// to be mistaken for a working one.
pub fn dispatch(tag: u8, request: []const u8) DispatchError!i32 {
    const connector = Connector.fromTag(tag) orelse return DispatchError.UnknownConnector;
    if (!connector.isImplemented()) return DispatchError.NotImplemented;
    _ = request;
    // Unreachable while IMPLEMENTED_COUNT is 0. When a transport lands, hand
    // the payload to the FFI core here (see main.zig).
    return 0;
}

test "the Hexadeca set has exactly sixteen members" {
    try std.testing.expectEqual(@as(usize, 16), CONNECTOR_COUNT);
}

test "ordinals are dense and stable" {
    inline for (@typeInfo(Connector).@"enum".fields, 0..) |f, i| {
        try std.testing.expectEqual(@as(u8, @intCast(i)), f.value);
    }
}

test "an out-of-range tag is rejected, not coerced" {
    try std.testing.expect(Connector.fromTag(16) == null);
    try std.testing.expect(Connector.fromTag(255) == null);
    try std.testing.expect(Connector.fromTag(0) != null);
}

test "an unimplemented connector never reports success" {
    inline for (@typeInfo(Connector).@"enum".fields) |f| {
        const c: Connector = @enumFromInt(f.value);
        if (!c.isImplemented()) {
            try std.testing.expectError(DispatchError.NotImplemented, dispatch(f.value, "{}"));
        }
    }
}

test "the implemented count matches what the connectors report" {
    // Fails the moment a transport lands without config/connectors.ncl being
    // updated, and equally if the manifest claims a transport that is absent.
    comptime var counted: usize = 0;
    inline for (@typeInfo(Connector).@"enum".fields) |f| {
        const c: Connector = @enumFromInt(f.value);
        if (c.isImplemented()) counted += 1;
    }
    try std.testing.expectEqual(IMPLEMENTED_COUNT, counted);
}

test "no transport is implemented yet, and dispatch says so" {
    try std.testing.expectEqual(@as(usize, 0), IMPLEMENTED_COUNT);
    inline for (@typeInfo(Connector).@"enum".fields) |f| {
        try std.testing.expectError(DispatchError.NotImplemented, dispatch(f.value, "{}"));
    }
}
