(use-modules (guix packages)
             (guix download)
             (guix build-system gnu)
             (guix licenses)
             (gnu packages)
             (gnu packages rust)
             (gnu packages zig)
             (gnu packages build-tools)
             (gnu packages elixir)
             (gnu packages erlang)
             (gnu packages idris))

(package
  (name "idaptik-ums-env")
  (version "0.1.0")
  (source #f)
  (build-system gnu-build-system)
  (native-inputs
   (list rust zig just idris2 elixir erlang))
  (synopsis "Development environment for Universal Modding Studio")
  (description "Provides toolchains required by idaptik-ums.")
  (home-page "https://github.com/metadatastician/idaptik-ums")
  (license gpl3+))
