// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2025-2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
//
// @generated by `just gen` from config/vocab.ncl and config/verbs.ncl.
// DO NOT EDIT BY HAND — `just gen-check` fails if this file drifts.
//
//! The closed worlds of the IDApTIK level object graph, and the verb registry.
//!
//! Closed worlds are what make generation decidable (ADR-0001): the relational
//! engine enumerates over these when an edit leaves a field fresh.

use crate::microkanren::{Goal, Term, membero};

/// One verb's contract: its ordered arguments, which are required, and the
/// finite domain of each argument that ranges over a closed world.
///
/// `args` is ordered because JSON key order is wire-significant and because
/// `solve()` binds its positional arguments in exactly this order.
#[derive(Clone, Copy, Debug)]
pub struct VerbSpec {
    pub name: &'static str,
    pub doc: &'static str,
    /// The state collection this verb appends to, or the field it sets.
    pub collection: &'static str,
    pub args: &'static [&'static str],
    pub required: &'static [&'static str],
    pub domains: &'static [(&'static str, &'static [&'static str])],
}

impl VerbSpec {
    /// The finite domain of `arg`, or `None` when the caller must supply it
    /// (ids and geometry are the proposer's job, not the kernel's).
    pub fn domain(&self, arg: &str) -> Option<&'static [&'static str]> {
        self.domains
            .iter()
            .find(|(a, _)| *a == arg)
            .map(|(_, d)| *d)
    }
}

/// The closed verb surface. Order is the schema's `oneOf` order.
pub const VERBS: [VerbSpec; 10] = [
    VerbSpec {
        name: "add_zone",
        doc: "Declare a zone: a worldX interval with a security tier.",
        collection: "zones",
        args: &["id", "securityTier", "worldXStart", "worldXEnd", "segment"],
        required: &["id", "securityTier", "worldXStart", "worldXEnd"],
        domains: &[("segment", &ZONE_SEGMENTS)],
    },
    VerbSpec {
        name: "add_device",
        doc: "Place a device of a known kind in a declared zone.",
        collection: "devices",
        args: &["id", "kind", "zone", "worldX"],
        required: &["id", "kind", "zone", "worldX"],
        domains: &[("kind", &DEVICE_KINDS)],
    },
    VerbSpec {
        name: "add_guard",
        doc: "Place a security guard of a known rank in a declared zone.",
        collection: "guards",
        args: &["id", "rank", "zone"],
        required: &["id", "rank", "zone"],
        domains: &[("rank", &GUARD_RANKS)],
    },
    VerbSpec {
        name: "add_dog",
        doc: "Place a patrol dog of a known breed in a declared zone.",
        collection: "dogs",
        args: &["id", "breed", "zone"],
        required: &["id", "breed", "zone"],
        domains: &[("breed", &DOG_BREEDS)],
    },
    VerbSpec {
        name: "add_drone",
        doc: "Place a drone of a known archetype in a declared zone.",
        collection: "drones",
        args: &["id", "archetype", "zone"],
        required: &["id", "archetype", "zone"],
        domains: &[("archetype", &DRONE_ARCHETYPES)],
    },
    VerbSpec {
        name: "add_npc",
        doc: "Place an ambient civilian NPC in a declared zone.",
        collection: "npcs",
        args: &["id", "role", "zone"],
        required: &["id", "role", "zone"],
        domains: &[("role", &NPC_ROLES)],
    },
    VerbSpec {
        name: "add_character",
        doc: "Place a named character: an ActorArchetype + Modifier pair.",
        collection: "characters",
        args: &["id", "archetype", "modifier", "zone"],
        required: &["id", "archetype", "modifier", "zone"],
        domains: &[
            ("archetype", &CHARACTER_ARCHETYPES),
            ("modifier", &CHARACTER_MODIFIERS),
        ],
    },
    VerbSpec {
        name: "add_item",
        doc: "Place an object/item of a known category in a declared zone.",
        collection: "items",
        args: &["id", "category", "zone"],
        required: &["id", "category", "zone"],
        domains: &[("category", &ITEM_CATEGORIES)],
    },
    VerbSpec {
        name: "set_mission",
        doc: "Set the mission block. Its internals remain game-owned.",
        collection: "mission",
        args: &["mission"],
        required: &["mission"],
        domains: &[],
    },
    VerbSpec {
        name: "set_physical",
        doc: "Set the physical-setup block. Its internals remain game-owned.",
        collection: "physical",
        args: &["physical"],
        required: &["physical"],
        domains: &[],
    },
];

/// Look up a verb by name.
pub fn verb(name: &str) -> Option<&'static VerbSpec> {
    VERBS.iter().find(|v| v.name == name)
}
/// `device_kinds`, generated from `config/vocab.ncl`.
pub const DEVICE_KINDS: [&str; 12] = [
    "Laptop",
    "Desktop",
    "Server",
    "Router",
    "Switch",
    "Firewall",
    "Camera",
    "AccessPoint",
    "PatchPanel",
    "PowerSupply",
    "PhoneSystem",
    "FibreHub",
];
/// `guard_ranks`, generated from `config/vocab.ncl`.
pub const GUARD_RANKS: [&str; 8] = [
    "BasicGuard",
    "Enforcer",
    "AntiHacker",
    "Sentinel",
    "Assassin",
    "EliteGuard",
    "SecurityChief",
    "RivalHacker",
];
/// `dog_breeds`, generated from `config/vocab.ncl`.
pub const DOG_BREEDS: [&str; 3] = ["Patrol", "Bloodhound", "RoboDog"];
/// `drone_archetypes`, generated from `config/vocab.ncl`.
pub const DRONE_ARCHETYPES: [&str; 3] = ["Helper", "Hunter", "Killer"];
/// `wiring_types`, generated from `config/vocab.ncl`.
pub const WIRING_TYPES: [&str; 5] = [
    "PatchPanel",
    "SwitchBackplane",
    "ServerRack",
    "FibreSplicing",
    "PBXComms",
];
/// `npc_roles`, generated from `config/vocab.ncl`.
pub const NPC_ROLES: [&str; 8] = [
    "Pedestrian",
    "Shopkeeper",
    "Resident",
    "Doorman",
    "StreetVendor",
    "Busker",
    "Commuter",
    "Concierge",
];
/// `character_archetypes`, generated from `config/vocab.ncl`.
pub const CHARACTER_ARCHETYPES: [&str; 8] = [
    "Protagonist",
    "Handler",
    "Fixer",
    "Contact",
    "Insider",
    "Rival",
    "Mark",
    "Bystander",
];
/// `character_modifiers`, generated from `config/vocab.ncl`.
pub const CHARACTER_MODIFIERS: [&str; 8] = [
    "Unarmed",
    "Armed",
    "Disguised",
    "Alerted",
    "Wounded",
    "Corrupt",
    "Loyal",
    "Undercover",
];
/// `item_categories`, generated from `config/vocab.ncl`.
pub const ITEM_CATEGORIES: [&str; 8] = [
    "Keycard",
    "Document",
    "Weapon",
    "Tool",
    "Loot",
    "Consumable",
    "Container",
    "Contraband",
];
/// `zone_segments`, generated from `config/vocab.ncl`.
pub const ZONE_SEGMENTS: [&str; 8] = [
    "Lan",
    "Dmz",
    "Internal",
    "Iot",
    "Management",
    "Scada",
    "Isp",
    "Service",
];
/// Goal: `t` is a member of `domain`. The `membero`-style domain relation
/// that makes an out-of-vocabulary value ungeneratable rather than merely
/// detectable.
pub fn in_domain(t: Term, domain: &[&str]) -> Goal {
    let items: Vec<Term> = domain.iter().map(|s| Term::str(*s)).collect();
    membero(t, &items)
}
