// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2025-2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
//
// @generated by `just gen` from config/connectors.ncl.
// DO NOT EDIT BY HAND — `just gen-check` fails if this file drifts.
//
//! The Hexadeca-Connector wire order, Rust side.
//!
//! The ordinal is the wire contract: a connector tag crosses the FFI boundary
//! as a `u8`. Zig, Rust and Idris2 are all generated from
//! `config/connectors.ncl`, and `tests/hexadeca_wire_order.rs` proves the
//! three agree — a silent disagreement would dispatch every call to the wrong
//! handler without anything crashing.

/// A protocol in the sixteen-member Hexadeca set.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
#[repr(u8)]
pub enum Connector {
    /// gRPC service surface.
    Grpc = 0,
    /// GraphQL query surface.
    Graphql = 1,
    /// JSON-in/JSON-out over HTTP — the shape idaptik-ffi already speaks, and the intended first transport for the UMS<->game DLC seam.
    Rest = 2,
    /// FlatBuffers zero-copy payloads.
    Flatbuffers = 3,
    /// Bebop binary records.
    Bebop = 4,
    /// JSON-RPC 2.0 — the intended framing for an editor driving ai-edit `solve` and `check`.
    Jsonrpc = 5,
    /// Duplex session transport (the game's session relay speaks this).
    Websocket = 6,
    /// Pub/sub telemetry.
    Mqtt = 7,
    /// tRPC-style typed procedure calls.
    Trpc = 8,
    /// Cap'n Proto RPC.
    Capnproto = 9,
    /// SOAP envelopes (legacy interop).
    Soap = 10,
    /// VerisimDB REST surface.
    VerisimdbRest = 11,
    /// Build Server Protocol.
    Bsp = 12,
    /// Source Code Index Protocol.
    Scip = 13,
    /// Content-addressed DLC distribution.
    Ipfs = 14,
    /// Arrow Flight bulk transfer.
    ArrowFlight = 15,
}

/// Every connector, in wire order.
pub const ALL: [Connector; 16] = [
    Connector::Grpc,
    Connector::Graphql,
    Connector::Rest,
    Connector::Flatbuffers,
    Connector::Bebop,
    Connector::Jsonrpc,
    Connector::Websocket,
    Connector::Mqtt,
    Connector::Trpc,
    Connector::Capnproto,
    Connector::Soap,
    Connector::VerisimdbRest,
    Connector::Bsp,
    Connector::Scip,
    Connector::Ipfs,
    Connector::ArrowFlight,
];

pub const CONNECTOR_COUNT: usize = 16;
pub const IMPLEMENTED_COUNT: usize = 0;

impl Connector {
    /// The wire tag. This value is the contract.
    pub fn tag(self) -> u8 {
        self as u8
    }

    /// Decode a wire tag. `None` for an out-of-range byte, so a version
    /// mismatch is detected rather than dispatched.
    pub fn from_tag(tag: u8) -> Option<Connector> {
        ALL.get(tag as usize).copied()
    }

    pub fn name(self) -> &'static str {
        match self {
            Connector::Grpc => "grpc",
            Connector::Graphql => "graphql",
            Connector::Rest => "rest",
            Connector::Flatbuffers => "flatbuffers",
            Connector::Bebop => "bebop",
            Connector::Jsonrpc => "jsonrpc",
            Connector::Websocket => "websocket",
            Connector::Mqtt => "mqtt",
            Connector::Trpc => "trpc",
            Connector::Capnproto => "capnproto",
            Connector::Soap => "soap",
            Connector::VerisimdbRest => "verisimdb_rest",
            Connector::Bsp => "bsp",
            Connector::Scip => "scip",
            Connector::Ipfs => "ipfs",
            Connector::ArrowFlight => "arrow_flight",
        }
    }

    /// Whether a real handler exists. A connector without one must never
    /// report success.
    pub fn is_implemented(self) -> bool {
        match self {
            Connector::Grpc => false,
            Connector::Graphql => false,
            Connector::Rest => false,
            Connector::Flatbuffers => false,
            Connector::Bebop => false,
            Connector::Jsonrpc => false,
            Connector::Websocket => false,
            Connector::Mqtt => false,
            Connector::Trpc => false,
            Connector::Capnproto => false,
            Connector::Soap => false,
            Connector::VerisimdbRest => false,
            Connector::Bsp => false,
            Connector::Scip => false,
            Connector::Ipfs => false,
            Connector::ArrowFlight => false,
        }
    }
}
